### ISSUE TITLE
Bouncycastle now includes a TLS provider so don't think this is necessary any more?

### ISSUE THREAD

**Issue by anotherdave** [tobszarny/ssl-provider-jvm16#1]
Hi, thanks for providing this tool, but now that Bouncycastle includes its own JSSE provider I don't think it is necessary any more. I tested with BouncyCastleProvider and BouncyCastleJsseProvider from BC release 1.58 installed in java.security, and was able to get rid of the "unsupported curve id: 29" message and connect to SQL Server 2016 OK.

**Comment by tobszarny** [comment]
Thanks for pointing this out.  Before BC 1.8 which was released on August 18 2017, there was no out of the box non-proprietary solution hence the implementation. I'm glad to hear The Legion of The Bouncy Castle finally provided JSSE implementation.
